defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  job:
    chdir: true
  job_logging:
    formatters:
      colorlog:
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red
  run:
    dir: ./outputs/${run_name}
  sweep:
    dir: ./outputs/multirun/${model_size}
    subdir: ${run_name}

# experiment config
data_path: /home/pl487/memorization/data
run_name: pythia-deduped-${model_size}-${revision}_${now:%Y-%m-%d}T${now:%H-%M-%S}
seed: 42

# model config
model_size: '???'
revision: '???'
cache_dir: .model_cache
accelerator: gpu
precision: bf16-true
deterministic: true
tf32_mode: high

# data config
batch_size: 32
multiprocessing_context: null
write_interval: 10
only_sequence_surprisal: false